openapi: 3.0.0
info:
  description: These RESTFUL endpoints are to retrieve Exclusion detail information
  version: "1.0"
  title: Exclusions API
  license:
    {}
tags:
  - name: Exclusions Object View
    description: Exclusions Operations
  - name: basic-error-controller
    description: Basic Error Controller
paths:
  "/msam/v1/exclusions/{exclusionDetails}":
    get:
      tags:
        - Exclusions Object View
      summary: Exclusions View Details
      operationId: getExclusionDetailsUsingGET
      parameters:
        - name: exclusionDetails
          in: path
          description: SAM Number+agency+type+ctCode. All fields are '+' separated. Null
            elements are replaced by 'NA'
          required: true
          schema:
            type: string
        - name: api_key
          in: query
          description: API KEY
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ExclusionsInfoResource"
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
servers:
  - url: //***REMOVED***/prodlike
components:
  schemas:
    ExclusionsInfoResource:
      type: object
      properties:
        exclusionDetails:
          $ref: "#/components/schemas/ExclusionDetails"
        links:
          type: array
          items:
            $ref: "#/components/schemas/Link"
    Address:
      type: object
      properties:
        address1:
          type: string
        address2:
          type: string
        addressCity:
          type: string
        addressState:
          type: string
        addressZip:
          type: string
        addressZipPlus4:
          type: string
        country:
          type: string
    ExclusionDetails:
      type: object
      properties:
        activateDate:
          type: string
        additionalComments:
          type: string
        classificationType:
          type: string
        crossReferenceType:
          type: string
        crossReferences:
          type: array
          items:
            $ref: "#/components/schemas/ExclusionDetails"
        ctCode:
          type: string
        dnbInvestigationStatus:
          type: string
        empty:
          type: boolean
        excludingAgency:
          type: string
        exclusionProgram:
          type: string
        exclusionStatus:
          type: string
        exclusionType:
          type: string
        identityInfo:
          $ref: "#/components/schemas/IdentificationInformation"
        moreLocations:
          type: array
          items:
            $ref: "#/components/schemas/Address"
        recordCreateDate:
          type: string
        recordUpdateDate:
          type: string
        samNumber:
          type: string
        terminationDate:
          type: string
        vesselDetails:
          $ref: "#/components/schemas/VesselDetails"
    ModelAndView:
      type: object
      properties:
        empty:
          type: boolean
        model:
          type: object
        modelMap:
          type: object
          additionalProperties:
            type: object
        reference:
          type: boolean
        status:
          type: string
          enum:
            - "100"
            - "101"
            - "102"
            - "103"
            - "200"
            - "201"
            - "202"
            - "203"
            - "204"
            - "205"
            - "206"
            - "207"
            - "208"
            - "226"
            - "300"
            - "301"
            - "302"
            - "302"
            - "303"
            - "304"
            - "305"
            - "307"
            - "308"
            - "400"
            - "401"
            - "402"
            - "403"
            - "404"
            - "405"
            - "406"
            - "407"
            - "408"
            - "409"
            - "410"
            - "411"
            - "412"
            - "413"
            - "413"
            - "414"
            - "414"
            - "415"
            - "416"
            - "417"
            - "418"
            - "419"
            - "420"
            - "421"
            - "422"
            - "423"
            - "424"
            - "426"
            - "428"
            - "429"
            - "431"
            - "451"
            - "500"
            - "501"
            - "502"
            - "503"
            - "504"
            - "505"
            - "506"
            - "507"
            - "508"
            - "509"
            - "510"
            - "511"
        view:
          $ref: "#/components/schemas/View"
        viewName:
          type: string
    VesselDetails:
      type: object
      properties:
        callSign:
          type: string
        flag:
          type: string
        grt:
          type: string
        owner:
          type: string
        secondaryAddress:
          $ref: "#/components/schemas/Address"
        tonnage:
          type: string
        type:
          type: string
    View:
      type: object
      properties:
        contentType:
          type: string
    Link:
      type: object
      properties:
        href:
          type: string
        rel:
          type: string
        templated:
          type: boolean
    IdentificationInformation:
      type: object
      properties:
        address:
          $ref: "#/components/schemas/Address"
        cageCode:
          type: string
        companyName:
          type: string
        duns:
          type: string
        duns4:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        middleName:
          type: string
        npi:
          type: string
        prefix:
          type: string
        suffix:
          type: string