

TMSS 2.0 Rate Query API Guide










 
Trademark Acknowledgement
All trademarks, registered trademarks, or service marks belong to their respective holders. Use of a term in this document should not be regarded as affecting the validity of any trademark or service mark. Any information or technology described herein that is the intellectual property of the trademark’s holder may not be duplicated, disseminated, or used without the specific permission of the property owner. The authors disclaim any proprietary interest in trademarks and trade names other than their own trademarks and trade names.

 
Document History
Version	Description	Date
1.0	Initial Release	03/24/2021
		
		
		
 
Table of Contents
Introduction	6
Intended Audience	6
Summary of Major Changes	6
Document Overview	6
Scope	6
API Overview	6
ratequeryhhg	7
Call Purpose and Related Operation	7
API Details	7
General API Structure	7
API url(s)	7
Test url(s)	7
Production urls	7
Accessing the API	8
To begin using this API, you will need to register for an API Key. You can sign up for an API key here: API key signup page on api.data.gov.	8
After registration, you will need to provide this API key in the x-api-key HTTP header with every API request.	8
Testing the API	8
API Feature Specifications	9
ratequeryhhg	9
API Specification	9
 	9
Request	9
Response	9
HHTP Response Codes	9
The API will return one of the following responses:	9
Sample Request and Response	10



 
Introduction
This document provides detailed technical information about the Rate query API offered by the TMSS 2.0. These services make use of industry standard methods for API authentication and connectivity, which should make it easier and faster for developers to interface Federal agency with TMSS 2.0. The following API is offered by TMSS 2.0:
●	(ratequeryhhg) https://api.gsa.gov/tmss/hhgratequery 
This API can be used to retrieve shipment cost for a regular Household Goods (HHG) shipment or for an Extended Storage (EXSTG) shipment.
Intended Audience
This document is intended for Registered Federal agency customers in TMSS 2.0, including managers, developers, security and support staff, who will be involved with connecting their applications to TMSS 2.0. 
Summary of Major Changes
<None>
Document Overview
This document captures the specifications for the TMSS 2.0 Rate Query API to be consumed by Federal agency customers.
This document is organized by the following major sections:
●	Introduction
●	API Details
●	API Feature Specifications
●	Data Dictionary and Validation Rules
●	Performance
●	Error Codes
Scope
This document serves as the Interface Guide between TMSS 2.0 and Federal Agency customer systems, containing a description of the operations to be provided by the TMSS 2.0 Rate Query API. 
API Overview
The following table show the purpose of the API call and the related operations:
ratequeryhhg
Call Purpose and Related Operation
Purpose	Related Operation
To get the shipment cost including Storage in Transit cost for a domestic or for an International HHG shipment	Return the costs in the specified format
To get the Extended Storage cost for a HHG shipment	Return the costs in the specified format

API Details
This section describes the structure of the TMSS 2.0 Rate Query API, how it can be used by Federal Agency Customer system, and to obtain access to the API.
General API Structure
The ratequeryhhg provides Federal Agency customers with a secure way to connect to TMSS 2.0 Rate Query API endpoints.  The connection to the API endpoints is secured and authenticated using the registered token provided by api.data.gov
API url(s)
The TMSS 2.0 Rate Query API urls are as follows: 
Test url(s)
1.	ratequeryhhg : https://api.gsa.gov/tmsspreprod/hhgratequery
Production urls
1.	ratequeryhhg : https://api.gsa.gov/tmss/hhgratequery
 
Accessing the API
To begin using this API, you will need to register for an API Key. You can sign up for an API key here: API key signup page on api.data.gov.
After registration, you will need to provide this API key in the x-api-key HTTP header with every API request.

HTTP Header Name	Description
x-api-key	API key from api.data.gov. For sample purposes, you can use DEMO_KEY as an API key.

Testing the API
In order to system test, integration test, and smoke test API you will need use the API urls mentioned above by passing the API token obtained from api.data.gov. 

 
API Feature Specifications
ratequeryhhg
API Specification
 
Request
All request payloads must be in JSON data structure specified in the Data dictionary section of this document.
Response
All response must be in JSON data structure specified in the Data dictionary section of this document.

HHTP Response Codes
The API will return one of the following responses:
Status code	Description
200	OK (Successful)
400	Bad Request
404	Not Found
408	Request Timeout
413	Payload too large
417	Expectation Failed
429	Too many requests
500	Internal Server Error
502	Bad Gateway
503	Service Unavailable
504	Gateway Timeout

 
Sample Request and Response
Request URL: https://api.gsa.gov/tmss/hhgratequery

Request Payload for a HHG Domestic Shipment:
{ 
   "agencyLocationCode": 697,
    "queryType":"HHGAPI",
    "pickupDate":"2020-04-12",
    "shipmentType":"General",
    "sroId":"GENRL",
    "containerizedShipments":false,
    "vehicleClass":"Class 1",
    "estimatedWeight": 10000,
    "originZip":"32714",
    "originProvince":null,
    "destinationZip":"23059",
    "destinationProvince":null,
    "originCountryCode":"US00",
    "destinationCountryCode":"US00",
    "miles": 100,
    "uabWeight":150
}

Response for a HHG Domestic Shipment:
{
       "agencyLocationCode": 697,
        "queryType": "HHGAPI",
        "pickupDate": "2020-04-12T00:00:00.000+0000",
        "shipmentType": "General",
        "sroId": "GENRL",
        "containerizedShipments": false,
        "vehicleClass": "Class 1",
        "estimatedWeight": 10000,
        "originZip": "32714",
        "originProvince": null,
        "destinationZip": "23059",
        "destinationProvince": null,
        "originCountryCode": "US00",
        "destinationCountryCode": "US00",
        "miles": 739.0,
        "uabWeight": 150,
        "rateId": 4265664,
        "queryId": 4488,
        "rateType": "G",
        "scac": "(New) BUSV",
        "zefflag": false,
        "companyName": "BURNHAM SERVICE COMPANY INC",
        "telephone": "800-955-5421",
        "socioEconomicInd": "s",
        "tender": "N613",
        "csi": "0.00",
        "vi": "33.4030",
        "surfacePercentage": 37,
        "surfaceCharge": "7367.75",
        "uabPercentage": 0,
        "uabCharge": "0.00",
        "vehicleCharge": "1101.11",
        "totalCharge": "8468.86",
        "sitRatePercentage": 47,
        "thirtyDayCharge": "3457.32",
        "sixtyDayCharge": "4289.22",
        "ninetyDayCharge": "5121.12",
        "sitOrigin185ACharge": "658.47",
        "sitOrigin185BCharge": "27.73",
        "sitOrigin210ACharge": "1994.68",
        "sitDest185ACharge": "658.47",
        "sitDest185BCharge": "27.73",
        "sitDest210ACharge": "1994.68",
        "originThirtyDayCharge": "3669.29",
        "originSixtyDayCharge": "4585.79",
        "originNinetyDayCharge": "5502.29",
        "exsPackagingCharge": null,
        "exsMonthlyStorageCharge": null,
        "exsWarehouseCharge": null,
        "exsTotal1MonthCharge": null,
        "exsTotal6MonthCharge": null,
        "exsTotal12MonthCharge": null,
        "exsDeliveryWithin50Miles": null,
        "exsDeliveryHandlingOut": null,
        "exsDeliveryOver50Miles": null,
        "exsDiscountApplied": null,
        "rateEffectiveDate": "2019-05-01T05:00:00.000+0000",
        "rateExpiryDate": "2020-05-31T05:00:00.000+0000"

}

Request Payload for a HHG International Shipment:
{  
    "agencyLocationCode": 697,
    "queryType":"HHGAPI",
    "pickupDate":"2020-04-12",
    "shipmentType":"General",
    "sroId":"GENRL",
    "containerizedShipments":false,
    "vehicleClass":"Class 1",
    "estimatedWeight": 10000,
    "originZip":"32714",
    "originProvince":null,
    "destinationZip":null,
    "destinationProvince":null,
    "originCountryCode":"US00",
    "destinationCountryCode":"1250",
    "miles": 100,
    "uabWeight":150
}

Response for a HHG International Shipment:
{
       "agencyLocationCode": 697,
        "queryType": "HHGAPI",
        "pickupDate": "2020-04-12T00:00:00.000+0000",
        "shipmentType": "General",
        "sroId": "GENRL",
        "containerizedShipments": false,
        "vehicleClass": "Class 1",
        "estimatedWeight": 10000,
        "originZip": "32714",
        "originProvince": null,
        "destinationZip": null,
        "destinationProvince": null,
        "originCountryCode": "US00",
        "destinationCountryCode": "1250",
        "miles": 0.0,
        "uabWeight": 150,
        "rateId": 3971539,
        "queryId": 4430,
        "rateType": "G",
        "scac": "STVF",
        "zefflag": false,
        "companyName": "STEVENS INTERNATIONAL FORWARDE",
        "telephone": "800-426-1348",
        "socioEconomicInd": null,
        "tender": "N701",
        "csi": "108.07",
        "vi": "111.1036",
        "surfacePercentage": 276,
        "surfaceCharge": "28254.12",
        "uabPercentage": 1575,
        "uabCharge": "1243.09",
        "vehicleCharge": "7200.00",
        "totalCharge": "36697.21",
        "sitRatePercentage": 110,
        "thirtyDayCharge": "907.50",
        "sixtyDayCharge": "1177.00",
        "ninetyDayCharge": "1446.50",
        "sitOrigin185ACharge": "0.00",
        "sitOrigin185BCharge": "0.00",
        "sitOrigin210ACharge": "1186.90",
        "sitDest185ACharge": "0.00",
        "sitDest185BCharge": "0.00",
        "sitDest210ACharge": "330.00",
        "originThirtyDayCharge": "2191.20",
        "originSixtyDayCharge": "2752.20",
        "originNinetyDayCharge": "3313.20",
        "exsPackagingCharge": null,
        "exsMonthlyStorageCharge": null,
        "exsWarehouseCharge": null,
        "exsTotal1MonthCharge": null,
        "exsTotal6MonthCharge": null,
        "exsTotal12MonthCharge": null,
        "exsDeliveryWithin50Miles": null,
        "exsDeliveryHandlingOut": null,
        "exsDeliveryOver50Miles": null,
        "exsDiscountApplied": null,
        "rateEffectiveDate": "2019-05-01T05:00:00.000+0000",
        "rateExpiryDate": "2020-04-30T05:00:00.000+0000"
}


Request Payload for a HHG Extended Storage Shipment:

{
   "agencyLocationCode": 697,
   "queryType":"HHG",
   "pickupDate":"2021-03-25",
   "rateType":"Extended Storage",
   "sroId":71,
   "containerizedShipments":false,
   "estimatedWeight":"5000",
   "originZipId":29510,
   "originProvince":null,
   "destinationZipId":null,
   "destinationProvince":null,
   "originCountryId":326,
   "destinationCountryId":null,
}


Response for a HHG Extended Storage Shipment:

{
   "rateId":139155408,
   "rateType":"G",
   "scac":"INIC",
   "carrierId":218,
   "zefflag":true,
   "companyName":"INTERSTATE INTERNATIONAL INC",
   "telephone":"8009991001",
   "tender":"XE21",
   "csi":null,
   "vi":null,
   "surfacePercentage":null,
   "surfaceCharge":null,
   "uabPercentage":null,
   "uabCharge":null,
   "vehicleCharge":null,
   "totalCharge":null,
   "estimatedCost":null,
   "sitRatePercentage":null,
   "thirtyDayCharge":null,
   "sixtyDayCharge":null,
   "ninetyDayCharge":null,
   "sitOrigin185ACharge":null,
   "sitOrigin185BCharge":null,
   "sitOrigin210ACharge":null,
   "sitDest185ACharge":null,
   "sitDest185BCharge":null,
   "sitDest210ACharge":null,
   "originThirtyDayCharge":null,
   "originSixtyDayCharge":null,
   "originNinetyDayCharge":null,
   "queryId":3059,
   "exsPackagingCharge":"2800.00",
   "exsMonthlyStorageCharge":"300.00",
   "exsWarehouseCharge":"300.00",
   "exsTotal1MonthCharge":"3400.00",
   "exsTotal6MonthCharge":"4900.00",
   "exsTotal12MonthCharge":"6700.00",
   "exsDeliveryWithin50Miles":"1850.00",
   "exsDeliveryHandlingOut":"262.50",
   "exsDeliveryOver50Miles":"2051.93",
   "exsDiscountApplied":50,
   "sro":"EXSTG",
   "socioEconomicInd":null,
   "effectiveDate":"2020-11-01T04:00:00.000+0000",
   "expiryDate":"2021-04-30T04:00:00.000+0000",
 }
